version: '2'

services:
  web:
    build: .
      ports:
        - "8888:80"
    depends_on:
      - db
    env_file:
      - env

  db:
    image: mariadb:10.1.10
      ports:
        - "3306:3306"
      env_file:
        - env
      depends_on:
        - dbdata
      volumes_from:
        - dbdata

  dbdata:
    image: tianon/true
      volumes:
        - /var/lib/mysql
